name: ci
on:
  push:
    branches:
      - main
    paths:
      - '**.sol'

env:
  FOUNDRY_PROFILE: "ci"

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: actions/setup-node@v3
        with:
          node-version: 16.14
      
      - name: build node modules
        run: yarn install --non-interactive

      - name: lint contracts
        run: yarn prettier:check
    
      - name: install foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      
      - name: build contracts
        run: forge build

      - name: test contracts
        run: forge test
